name: GitHub Actions Demo
on:
  push:
    branches: main
    paths-ignore: [.github/**]
  pull_request:
    branches: main
  schedule:
    - cron: "15 6 * * 0"
  workflow_dispatch:
    inputs:
      environment:
        description: "Where to deploy"
        required: true
        type: environment
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: exercice1
        run: echo "${{ github.event_name }} // ${{ github.ref }}"
  Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: [build]
    steps:
      - id: test
        run: echo "Running in Test"
  Load-Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: [build]
    steps:
      - id: load-test
        run: echo "Running in Load Test"
  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    if: github.event.inputs.environment == 'Production'
    environment:
      name: Production
      url: https://www.tv2.no
    steps:
      - id: Prod
        run: echo "PROD !!!!"
