name: GitHub Actions Demo
on:
  push:
    branches: main
    paths-ignore: [.github/**]
  pull_request:
    branches: main
  schedule:
    - cron: "15 6 * * 0"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: exercice1
        run: echo "${{ github.event_name }} // ${{ github.ref }}"
