name: ReUse
on: [workflow_dispatch]

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      who-to-greet: "Super Juju"
  read-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
      - run: echo "${{ needs.call-workflow.outputs.current-time }}"
    
