name: Reusable workflow
on:
  workflow_call:
    inputs:
      who-to-greet:
        description: 'Who to greet'
        type: string
        required: true
        default: Juju
    outputs:
      current-time:
        description: "When the greeting was performed"
        value: ${{ jobs.reusable-job.outputs.current-time }}
jobs:
  reusable-job:
    runs-on: ubuntu-latest
    outputs:
      current-time: ${{ steps.time.outputs.time }}
    steps:
    - name: "Basic Hello"
      run: echo "Hello ${{ inputs.who-to-greet }}"
    - id: "time"
      run: echo "time=$(date)" >> $GITHUB_OUTPUT
